### ISSUE TITLE
Google Drive Connector install guide revisions

### ISSUE THREAD

**Issue by ruthaydt** [globusonline/docs.globus.org#172]
Comments based on staging version 8/9/17 - 9:23 am

- Do we want/need TOC?  Seems to break flow of doc.

- "Steps" subsection in Endpoint Installation section not showing up in TOC.   Guessing it's been assigned wrong heading level.

- Delete ":" from Steps: subsection in Registration of endpoint with Google section (not consistent w/ other sections and looks odd in TOC.

- Personally I wish that when I clicked a "go to" link it would open in a new window (or at least a new tab) if I'm going to do an action there.  Such as https://developers.globus.org/ and especially the google Developers Console.   Then I could keep reading my instructions while I work on the actions in the other window.    This is probably not consistent with how our docs behave, and maybe something I can set myself (or I can cut/paste the URL), but I keep forgetting and then when I go <- to the doc I've lost my place ... I always get repositioned at the top.

- Following up on previous bullet - instead of Developers Console with link I don't see, can the link be shown as it is for the Google API Manager?    Then it's easier for me to remember to cut/paste. 

- Should be Developers' Console (or Developer's Console or Developer Console) not Developers Console.

- In "Registration of endpoint with Google" , Step 6a, say "Display Name" not "display name" -- we always talk about it with caps in earlier text - cue the reader this is the same thing we set/used earlier.

**Comment by teresas** [comment]
- Since it's a decent length, I would recommend keeping the ToC since that is consistent with other pages. If preferred, we can move it to the top and have the page description text below it, but that doesn't really make sense since it's page description text and not part of the content included in the ToC
- At this time, because of how nanoc renders links we cannot open a link in another tab/window
- Changing "Developers" to "Developer Console" since it looks like that's how it comes up in a google search? Should be up on staging shortly
<img width="719" alt="screen shot 2017-08-10 at 10 19 42 am" src="https://user-images.githubusercontent.com/1242178/29177869-7f5ce522-7db5-11e7-8baf-eab71f4b6c52.png">
- I'm addressing "Steps" in ToC, Delete ":", visible Developer Console link, Display Name which should be up on staging shortly

**Comment by ruthaydt** [comment]
Reviewed and ready for production in my opinion
